language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "pypy3"
# command to install dependencies
install:
    - "pip install bitstring>=3.1.3"
    - "pip install pyflakes"
# command to run tests
script:
    - python setup.py test
    - pyflakes pybufrkit tests *.py
